apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker-compose.yml
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: folio-stripes
  name: folio-stripes
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: folio-stripes
    spec:
      containers:
      - env:
        - name: OKAPI_HOSTPORT
        - name: OKAPI_SCHEME
        - name: OKAPI_TENANT
        image: folio-stripes
        name: folio-stripes
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
