apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose/
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: okapi
  name: okapi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: okapi
    spec:
      containers:
      - env:
        - name: FOLIO_DATABASE
          value: folio
        - name: FOLIO_DATABASE_ROLE_USER
          value: folio
        - name: FOLIO_PASSWORD
          value: folio123
        - name: HAZELCAST_FILE
          value: /usr/local/bin/folio/okapi/hazelcast.xml
        - name: HAZELCAST_IP
          value: okapi
        - name: HAZELCAST_PORT
          value: "5701"
        - name: HAZELCAST_VERTX_PORT
          value: "5703"
        - name: INITDB
          value: "true"
        - name: OKAPI_CLUSTERHOST
          value: okapi
        - name: OKAPI_COMMAND
          value: cluster
        - name: OKAPI_HOST
          value: okapi
        - name: OKAPI_LOGLEVEL
          value: ERROR
        - name: OKAPI_NODENAME
          value: okapi
        - name: OKAPI_PORT
          value: "9130"
        - name: OKAPI_URL
          value: http://okapi:9130
        - name: PG_DATABASE
          value: okapi
        - name: PG_HOST
          value: folio-db
        - name: PG_PASSWORD
          value: okapi25
        - name: PG_PORT
          value: "5432"
        - name: PG_USERNAME
          value: okapi
        - name: POSTGRES_PASSWORD
          value: password
        - name: db.database
          value: folio
        - name: db.host
          value: folio-db
        - name: db.password
          value: folio123
        - name: db.port
          value: "5432"
        - name: db.username
          value: folio
        image: culibraries/okapi:v2.18.0
        name: folio-okapi
        ports:
        - containerPort: 9130
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/bin/folio/startup.sh
          name: okapi-claim0
      restartPolicy: Always
      volumes:
      - name: okapi-claim0
        persistentVolumeClaim:
          claimName: okapi-claim0
status: {}
