apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/creatorId: u-d8jfk
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: null
  finalizers:
  - kubernetes.io/pvc-protection
  name: folio-data-claim
  selfLink: /api/v1/namespaces/folio-q2/persistentvolumeclaims/folio-data-claim
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
  volumeName: folio-data-volume
status: {}
