apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/creatorId: u-d8jfk
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: "null"
  creationTimestamp: null
  name: pg-folio
  selfLink: /api/v1/namespaces/folio-q2/services/pg-folio
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    statefulset.kubernetes.io/pod-name: pgset-0
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
