apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["<xxx.xxx.xxx.xxx>"],"port":31990,"protocol":"TCP","serviceName":"folio-q2:stripes-nodeport","allNodes":true}]'
    field.cattle.io/targetWorkloadIds: '["daemonset:folio-q2:stripes"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: null
  name: stripes-nodeport
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: daemonset
    name: stripes
    uid: 689e4090-ac5b-11e8-8f98-005056bb5193
  selfLink: /api/v1/namespaces/folio-q2/services/stripes-nodeport
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 3000tcp01
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    workload.user.cattle.io/workloadselector: daemonSet-folio-q2-stripes
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
