apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    field.cattle.io/creatorId: u-foo
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-authtoken
  name: mod-authtoken
  selfLink: /apis/apps/v1beta2/namespaces/folio-q4/deployments/mod-authtoken
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 300
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-authtoken
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp:
      creationTimestamp: null
      labels:
        workload: folio_module
        workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-authtoken
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Djwt.signing.key=CorrectBatteryHorseStaple -Xmx256m
        image: folioorg/mod-authtoken:2.0.4
        imagePullPolicy: Always
        name: mod-authtoken
        resources:
          limits:
            memory: 1Gi
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
