apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "7"
    field.cattle.io/creatorId: u-foo
    field.cattle.io/publicEndpoints: '[{"addresses":["XX.XX.XXX.XXX"],"port":31332,"protocol":"TCP","serviceName":"folio-q4:mod-marccat-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-marccat
  name: mod-marccat
  selfLink: /apis/apps/v1beta2/namespaces/folio-q4/deployments/mod-marccat
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 300
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-marccat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp:
        field.cattle.io/ports: '[[{"containerPort":9403,"dnsName":"mod-marccat-nodeport","kind":"NodePort","name":"9403tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload: folio_module
        workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-marccat
    spec:
      containers:
      - image: folioorg/mod-marccat:1.2.0
        imagePullPolicy: Always
        name: mod-marccat
        ports:
        - containerPort: 9403
          name: 9403tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
