apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "19"
    field.cattle.io/creatorId: u-foo
    field.cattle.io/publicEndpoints: '[{"addresses":["XX.XX.XXX.XXX"],"port":30885,"protocol":"TCP","serviceName":"folio-q4:mod-agreements-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-agreements
  name: mod-agreements
  selfLink: /apis/apps/v1beta2/namespaces/folio-q4/deployments/mod-agreements
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 300
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-agreements
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp:
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"mod-agreements-nodeport","kind":"NodePort","name":"8080tcp01","protocol":"TCP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload: folio_module
        workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-agreements
    spec:
      containers:
      - env:
        - name: GRAILS_SERVER_HOST
          value: mod-agreements
        - name: GRAILS_SERVER_PORT
          value: "8080"
        - name: JAVA_OPTIONS
          value: -Xmx256m
        envFrom:
        - secretRef:
            name: db-connect
            optional: false
        image: folioorg/mod-agreements:1.0.2
        imagePullPolicy: Always
        name: mod-agreements
        ports:
        - containerPort: 8080
          name: 8080tcp01
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
