apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
    field.cattle.io/creatorId: u-foo
  creationTimestamp: null
  generation: 1
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-erm-usage-harvester
  name: mod-erm-usage-harvester
  selfLink: /apis/apps/v1beta2/namespaces/folio-q4/deployments/mod-erm-usage-harvester
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 300
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-erm-usage-harvester
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        cattle.io/timestamp:
      creationTimestamp: null
      labels:
        workload: folio_module
        workload.user.cattle.io/workloadselector: deployment-folio-q4-mod-erm-usage-harvester
    spec:
      containers:
      - env:
        - name: CONFIG
          value: '{"okapiUrl": "http://okapi:9130"}'
        - name: JAVA_OPTIONS
          value: -Xmx256m
        image: folioorg/mod-erm-usage-harvester:1.0.0
        imagePullPolicy: Always
        name: mod-erm-usage-harvester
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
