version: '3'
services:
  folio-db:
    image: postgres:9.6
    container_name: folio-db
    env_file:
      - ./config/folio-db.env
    volumes:
      - folio-pgdata:/var/lib/postgresql/data
      - ../../images/postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  okapi:
    image: okapi
    container_name: folio-okapi
    build:
      context: ../../images/okapi
      args:
        - OKAPI_TAG=${OKAPI_TAG}
    env_file:
      - ./config/folio-db.env
      - ./config/folio-okapi.env
    environment:
      - OKAPI_NODENAME=okapi
      - INITDB=${INITDB}
    expose:
      - 5701-5710
      - 54327
      - 9130
      - 9150
      - 4243
    ports:
      - ${OKAPI_PORT_HOST}:9130
    volumes:
      - ../../images/okapi/startup.sh:/usr/local/bin/folio/startup.sh
    depends_on:
      - folio-db
  folio-setup:
    image: foliosetup
    container_name: folio-setup
    build: ../../images/folio-setup
    env_file:
      - ./config/folio-setup.env
      - ./config/folio-okapi.env
    environment:
      - OKAPI_NODENAME=okapi
      - PLATFORM_COMPLETE_TAG=${PLATFORM_COMPLETE_TAG}
      - FOLIO_INSTALL_TAG=${FOLIO_INSTALL_TAG}
      - LOAD_SAMPLEDATA=${LOAD_SAMPLEDATA}
      - INITDB=${INITDB}
    depends_on:
      - okapi
      - folio-db
  mod-authtoken:
    image: ${MOD_AUTHTOKEN_ORG}/${MOD_AUTHTOKEN_MODULE}:${MOD_AUTHTOKEN_TAG}
    container_name: folio-mod-authtoken
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_AUTHTOKEN_ORG}
        - MODULE=${MOD_AUTHTOKEN_MODULE}
        - TAG=${MOD_AUTHTOKEN_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_AUTHTOKEN_ORG}
      - MODULE=${MOD_AUTHTOKEN_MODULE}
      - TAG=${MOD_AUTHTOKEN_TAG}
      - MODULE_URL=${MOD_AUTHTOKEN_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-calendar:
    image: ${MOD_CALENDAR_ORG}/${MOD_CALENDAR_MODULE}:${MOD_CALENDAR_TAG}
    container_name: folio-mod-calendar
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_CALENDAR_ORG}
        - MODULE=${MOD_CALENDAR_MODULE}
        - TAG=${MOD_CALENDAR_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_CALENDAR_ORG}
      - MODULE=${MOD_CALENDAR_MODULE}
      - TAG=${MOD_CALENDAR_TAG}
      - MODULE_URL=${MOD_CALENDAR_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-permissions:
    image: ${MOD_PERMISSION_ORG}/${MOD_PERMISSION_MODULE}:${MOD_PERMISSION_TAG}
    container_name: folio-mod-permissions
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_PERMISSION_ORG}
        - MODULE=${MOD_PERMISSION_MODULE}
        - TAG=${MOD_PERMISSION_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_PERMISSION_ORG}
      - MODULE=${MOD_PERMISSION_MODULE}
      - TAG=${MOD_PERMISSION_TAG}
      - MODULE_URL=${MOD_PERMISSION_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-login:
    image: ${MOD_LOGIN_ORG}/${MOD_LOGIN_MODULE}:${MOD_LOGIN_TAG}
    container_name: folio-mod-login
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_LOGIN_ORG}
        - MODULE=${MOD_LOGIN_MODULE}
        - TAG=${MOD_LOGIN_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_LOGIN_ORG}
      - MODULE=${MOD_LOGIN_MODULE}
      - TAG=${MOD_LOGIN_TAG}
      - MODULE_URL=${MOD_LOGIN_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-configuration:
    image: ${MOD_CONFIGURATION_ORG}/${MOD_CONFIGURATION_MODULE}:${MOD_CONFIGURATION_TAG}
    container_name: folio-mod-configuration
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_CONFIGURATION_ORG}
        - MODULE=${MOD_CONFIGURATION_MODULE}
        - TAG=${MOD_CONFIGURATION_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_CONFIGURATION_ORG}
      - MODULE=${MOD_CONFIGURATION_MODULE}
      - TAG=${MOD_CONFIGURATION_TAG}
      - MODULE_URL=${MOD_CONFIGURATION_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-users:
    image: ${MOD_USERS_ORG}/${MOD_USERS_MODULE}:${MOD_USERS_TAG}
    container_name: folio-mod-users
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_USERS_ORG}
        - MODULE=${MOD_USERS_MODULE}
        - TAG=${MOD_USERS_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_USERS_ORG}
      - MODULE=${MOD_USERS_MODULE}
      - TAG=${MOD_USERS_TAG}
      - MODULE_URL=${MOD_USERS_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-users-bl:
    image: ${MOD_USERSBL_ORG}/${MOD_USERSBL_MODULE}:${MOD_USERSBL_TAG}
    container_name: folio-mod-users-bl
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_USERSBL_ORG}
        - MODULE=${MOD_USERSBL_MODULE}
        - TAG=${MOD_USERSBL_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_USERSBL_ORG}
      - MODULE=${MOD_USERSBL_MODULE}
      - TAG=${MOD_USERSBL_TAG}
      - MODULE_URL=${MOD_USERSBL_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-user-import:
    image: ${MOD_USERIMPORT_ORG}/${MOD_USERIMPORT_MODULE}:${MOD_USERIMPORT_TAG}
    container_name: folio-mod-user-import
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_USERIMPORT_ORG}
        - MODULE=${MOD_USERIMPORT_MODULE}
        - TAG=${MOD_USERIMPORT_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_USERIMPORT_ORG}
      - MODULE=${MOD_USERIMPORT_MODULE}
      - TAG=${MOD_USERIMPORT_TAG}
      - MODULE_URL=${MOD_USERIMPORT_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-login-saml:
    image: ${MOD_LOGINSAML_ORG}/${MOD_LOGINSAML_MODULE}:${MOD_LOGINSAML_TAG}
    container_name: folio-mod-login-saml
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_LOGINSAML_ORG}
        - MODULE=${MOD_LOGINSAML_MODULE}
        - TAG=${MOD_LOGINSAML_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_LOGINSAML_ORG}
      - MODULE=${MOD_LOGINSAML_MODULE}
      - TAG=${MOD_LOGINSAML_TAG}
      - MODULE_URL=${MOD_LOGINSAML_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-inventory-storage:
    image: ${MOD_INVSTORAGE_ORG}/${MOD_INVSTORAGE_MODULE}:${MOD_INVSTORAGE_TAG}
    container_name: folio-mod-inventory-storage
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_INVSTORAGE_ORG}
        - MODULE=${MOD_INVSTORAGE_MODULE}
        - TAG=${MOD_INVSTORAGE_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_INVSTORAGE_ORG}
      - MODULE=${MOD_INVSTORAGE_MODULE}
      - TAG=${MOD_INVSTORAGE_TAG}
      - MODULE_URL=${MOD_INVSTORAGE_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-inventory:
    image: ${MOD_INVENTORY_ORG}/${MOD_INVENTORY_MODULE}:${MOD_INVENTORY_TAG}
    container_name: folio-mod-inventory
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_INVENTORY_ORG}
        - MODULE=${MOD_INVENTORY_MODULE}
        - TAG=${MOD_INVENTORY_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_INVENTORY_ORG}
      - MODULE=${MOD_INVENTORY_MODULE}
      - TAG=${MOD_INVENTORY_TAG}
      - MODULE_URL=${MOD_INVENTORY_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-codex-inventory:
    image: ${MOD_CODEXINVENTORY_ORG}/${MOD_CODEXINVENTORY_MODULE}:${MOD_CODEXINVENTORY_TAG}
    container_name: folio-mod-codex-inventory
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_CODEXINVENTORY_ORG}
        - MODULE=${MOD_CODEXINVENTORY_MODULE}
        - TAG=${MOD_CODEXINVENTORY_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_CODEXINVENTORY_ORG}
      - MODULE=${MOD_CODEXINVENTORY_MODULE}
      - TAG=${MOD_CODEXINVENTORY_TAG}
      - MODULE_URL=${MOD_CODEXINVENTORY_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-circulation-storage:
    image: ${MOD_CIRCULATIONSTORAGE_ORG}/${MOD_CIRCULATIONSTORAGE_MODULE}:${MOD_CIRCULATIONSTORAGE_TAG}
    container_name: folio-mod-circulation-storage
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_CIRCULATIONSTORAGE_ORG}
        - MODULE=${MOD_CIRCULATIONSTORAGE_MODULE}
        - TAG=${MOD_CIRCULATIONSTORAGE_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_CIRCULATIONSTORAGE_ORG}
      - MODULE=${MOD_CIRCULATIONSTORAGE_MODULE}
      - TAG=${MOD_CIRCULATIONSTORAGE_TAG}
      - MODULE_URL=${MOD_CIRCULATIONSTORAGE_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-circulation:
    image: ${MOD_CIRCULATION_ORG}/${MOD_CIRCULATION_MODULE}:${MOD_CIRCULATION_TAG}
    container_name: folio-mod-circulation
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_CIRCULATION_ORG}
        - MODULE=${MOD_CIRCULATION_MODULE}
        - TAG=${MOD_CIRCULATION_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_CIRCULATION_ORG}
      - MODULE=${MOD_CIRCULATION_MODULE}
      - TAG=${MOD_CIRCULATION_TAG}
      - MODULE_URL=${MOD_CIRCULATION_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-notify:
    image: ${MOD_NOTIFY_ORG}/${MOD_NOTIFY_MODULE}:${MOD_NOTIFY_TAG}
    container_name: folio-mod-notify
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_NOTIFY_ORG}
        - MODULE=${MOD_NOTIFY_MODULE}
        - TAG=${MOD_NOTIFY_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_NOTIFY_ORG}
      - MODULE=${MOD_NOTIFY_MODULE}
      - TAG=${MOD_NOTIFY_TAG}
      - MODULE_URL=${MOD_NOTIFY_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-notes:
    image: ${MOD_NOTES_ORG}/${MOD_NOTES_MODULE}:${MOD_NOTES_TAG}
    container_name: folio-mod-notes
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_NOTES_ORG}
        - MODULE=${MOD_NOTES_MODULE}
        - TAG=${MOD_NOTES_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_NOTES_ORG}
      - MODULE=${MOD_NOTES_MODULE}
      - TAG=${MOD_NOTES_TAG}
      - MODULE_URL=${MOD_NOTES_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-kb-ebsco:
    image: ${MOD_KBEBSCO_ORG}/${MOD_KBEBSCO_MODULE}:${MOD_KBEBSCO_TAG}
    container_name: folio-mod-kb-ebsco
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_KBEBSCO_ORG}
        - MODULE=${MOD_KBEBSCO_MODULE}
        - TAG=${MOD_KBEBSCO_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_KBEBSCO_ORG}
      - MODULE=${MOD_KBEBSCO_MODULE}
      - TAG=${MOD_KBEBSCO_TAG}
      - MODULE_URL=${MOD_KBEBSCO_URL}
      - START_CMD=${MOD_KBEBSCO_STARTCMD}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-codex-mux:
    image: ${MOD_CODEXMUX_ORG}/${MOD_CODEXMUX_MODULE}:${MOD_CODEXMUX_TAG}
    container_name: folio-mod-codex-mux
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_CODEXMUX_ORG}
        - MODULE=${MOD_CODEXMUX_MODULE}
        - TAG=${MOD_CODEXMUX_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_CODEXMUX_ORG}
      - MODULE=${MOD_CODEXMUX_MODULE}
      - TAG=${MOD_CODEXMUX_TAG}
      - MODULE_URL=${MOD_CODEXMUX_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-codex-ekb:
    image: ${MOD_CODEXEKB_ORG}/${MOD_CODEXEKB_MODULE}:${MOD_CODEXEKB_TAG}
    container_name: folio-mod-codex-ekb
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_CODEXEKB_ORG}
        - MODULE=${MOD_CODEXEKB_MODULE}
        - TAG=${MOD_CODEXEKB_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_CODEXEKB_ORG}
      - MODULE=${MOD_CODEXEKB_MODULE}
      - TAG=${MOD_CODEXEKB_TAG}
      - MODULE_URL=${MOD_CODEXEKB_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-vendors:
    image: ${MOD_VENDORS_ORG}/${MOD_VENDORS_MODULE}:${MOD_VENDORS_TAG}
    container_name: folio-mod-vendors
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_VENDORS_ORG}
        - MODULE=${MOD_VENDORS_MODULE}
        - TAG=${MOD_VENDORS_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_VENDORS_ORG}
      - MODULE=${MOD_VENDORS_MODULE}
      - TAG=${MOD_VENDORS_TAG}
      - MODULE_URL=${MOD_VENDORS_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-tags:
    image: ${MOD_TAGS_ORG}/${MOD_TAGS_MODULE}:${MOD_TAGS_TAG}
    container_name: folio-mod-tags
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_TAGS_ORG}
        - MODULE=${MOD_TAGS_MODULE}
        - TAG=${MOD_TAGS_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_TAGS_ORG}
      - MODULE=${MOD_TAGS_MODULE}
      - TAG=${MOD_TAGS_TAG}
      - MODULE_URL=${MOD_TAGS_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-feesfines:
    image: ${MOD_FEESFINES_ORG}/${MOD_FEESFINES_MODULE}:${MOD_FEESFINES_TAG}
    container_name: folio-mod-feesfines
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_FEESFINES_ORG}
        - MODULE=${MOD_FEESFINES_MODULE}
        - TAG=${MOD_FEESFINES_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_FEESFINES_ORG}
      - MODULE=${MOD_FEESFINES_MODULE}
      - TAG=${MOD_FEESFINES_TAG}
      - MODULE_URL=${MOD_FEESFINES_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-rtac:
    image: ${MOD_RTAC_ORG}/${MOD_RTAC_MODULE}:${MOD_RTAC_TAG}
    container_name: folio-mod-rtac
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_RTAC_ORG}
        - MODULE=${MOD_RTAC_MODULE}
        - TAG=${MOD_RTAC_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_RTAC_ORG}
      - MODULE=${MOD_RTAC_MODULE}
      - TAG=${MOD_RTAC_TAG}
      - MODULE_URL=${MOD_RTAC_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
  mod-finance:
    image: ${MOD_FINANCE_ORG}/${MOD_FINANCE_MODULE}:${MOD_FINANCE_TAG}
    container_name: folio-mod-finance
    build:
      context: ../../images/backend-module
      args:
        - ORG=${MOD_FINANCE_ORG}
        - MODULE=${MOD_FINANCE_MODULE}
        - TAG=${MOD_FINANCE_TAG}
    env_file:
      - ./config/folio-db.env
    environment:
      - OKAPI_URL=${OKAPI_URL}
      - OKAPI_TENANT=${OKAPI_TENANT}
      - ORG=${MOD_FINANCE_ORG}
      - MODULE=${MOD_FINANCE_MODULE}
      - TAG=${MOD_FINANCE_TAG}
      - MODULE_URL=${MOD_FINANCE_URL}
    depends_on:
      - okapi
      - folio-db
      - folio-setup
volumes:
  folio-pgdata:
