apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/publicEndpoints: '[{"addresses":["XX.XX.XXX.XXX"],"port":32200,"protocol":"TCP","serviceName":"folio-q4:stripes-nodeport","allNodes":true}]'
    field.cattle.io/targetWorkloadIds: '["daemonset:folio-q4:stripes"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: stripes-nodeport
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: daemonset
    name: stripes
    uid:
  selfLink: /api/v1/namespaces/folio-q4/services/stripes-nodeport
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: 3000tcp01
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    workload.user.cattle.io/workloadselector: daemonSet-folio-q4-stripes
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
