apiVersion: v1
data:
  HAZELCAST_FILE: /usr/local/bin/folio/okapi/hazelcast.xml
  HAZELCAST_IP: okapi
  HAZELCAST_PORT: "5701"
  HAZELCAST_VERTX_PORT: "5703"
  OKAPI_CLUSTERHOST: okapi
  OKAPI_COMMAND: cluster
  OKAPI_HOST: okapi
  OKAPI_LOGLEVEL: ERROR
  OKAPI_PORT: "9130"
  OKAPI_URL: http://okapi:9130
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: folio-setup-config-folio-okapi-env
  name: folio-setup-config-folio-okapi-env
