apiVersion: v1
data:
  FOLIO_DATABASE: folio
  FOLIO_DATABASE_ROLE_USER: folio
  FOLIO_PASSWORD: folio123
  PG_DATABASE: okapi
  PG_HOST: folio-db
  PG_PASSWORD: okapi25
  PG_PORT: "5432"
  PG_USERNAME: okapi
  POSTGRES_PASSWORD: password
  db.database: folio
  db.host: folio-db
  db.password: folio123
  db.port: "5432"
  db.username: folio
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mod-kb-ebsco-config-folio-db-env
  name: mod-kb-ebsco-config-folio-db-env
