apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose/
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: okapi
  name: okapi
spec:
  ports:
  - name: "9130"
    port: 9130
    targetPort: 9130
  selector:
    io.kompose.service: okapi
status:
  loadBalancer: {}
