apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert --out kompose/
    kompose.version: 1.16.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: okapi
  name: okapi
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: okapi
    spec:
      containers:
      - env:
        - name: FOLIO_DATABASE
          valueFrom:
            configMapKeyRef:
              key: FOLIO_DATABASE
              name: okapi-config-folio-db-env
        - name: FOLIO_DATABASE_ROLE_USER
          valueFrom:
            configMapKeyRef:
              key: FOLIO_DATABASE_ROLE_USER
              name: okapi-config-folio-db-env
        - name: FOLIO_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: FOLIO_PASSWORD
              name: okapi-config-folio-db-env
        - name: HAZELCAST_FILE
          valueFrom:
            configMapKeyRef:
              key: HAZELCAST_FILE
              name: okapi-config-folio-okapi-env
        - name: HAZELCAST_IP
          valueFrom:
            configMapKeyRef:
              key: HAZELCAST_IP
              name: okapi-config-folio-okapi-env
        - name: HAZELCAST_PORT
          valueFrom:
            configMapKeyRef:
              key: HAZELCAST_PORT
              name: okapi-config-folio-okapi-env
        - name: HAZELCAST_VERTX_PORT
          valueFrom:
            configMapKeyRef:
              key: HAZELCAST_VERTX_PORT
              name: okapi-config-folio-okapi-env
        - name: INITDB
        - name: OKAPI_CLUSTERHOST
          valueFrom:
            configMapKeyRef:
              key: OKAPI_CLUSTERHOST
              name: okapi-config-folio-okapi-env
        - name: OKAPI_COMMAND
          valueFrom:
            configMapKeyRef:
              key: OKAPI_COMMAND
              name: okapi-config-folio-okapi-env
        - name: OKAPI_HOST
          valueFrom:
            configMapKeyRef:
              key: OKAPI_HOST
              name: okapi-config-folio-okapi-env
        - name: OKAPI_LOGLEVEL
          valueFrom:
            configMapKeyRef:
              key: OKAPI_LOGLEVEL
              name: okapi-config-folio-okapi-env
        - name: OKAPI_NODENAME
          value: okapi
        - name: OKAPI_PORT
          valueFrom:
            configMapKeyRef:
              key: OKAPI_PORT
              name: okapi-config-folio-okapi-env
        - name: OKAPI_URL
          valueFrom:
            configMapKeyRef:
              key: OKAPI_URL
              name: okapi-config-folio-okapi-env
        - name: PG_DATABASE
          valueFrom:
            configMapKeyRef:
              key: PG_DATABASE
              name: okapi-config-folio-db-env
        - name: PG_HOST
          valueFrom:
            configMapKeyRef:
              key: PG_HOST
              name: okapi-config-folio-db-env
        - name: PG_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: PG_PASSWORD
              name: okapi-config-folio-db-env
        - name: PG_PORT
          valueFrom:
            configMapKeyRef:
              key: PG_PORT
              name: okapi-config-folio-db-env
        - name: PG_USERNAME
          valueFrom:
            configMapKeyRef:
              key: PG_USERNAME
              name: okapi-config-folio-db-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: okapi-config-folio-db-env
        - name: db.database
          valueFrom:
            configMapKeyRef:
              key: db.database
              name: okapi-config-folio-db-env
        - name: db.host
          valueFrom:
            configMapKeyRef:
              key: db.host
              name: okapi-config-folio-db-env
        - name: db.password
          valueFrom:
            configMapKeyRef:
              key: db.password
              name: okapi-config-folio-db-env
        - name: db.port
          valueFrom:
            configMapKeyRef:
              key: db.port
              name: okapi-config-folio-db-env
        - name: db.username
          valueFrom:
            configMapKeyRef:
              key: db.username
              name: okapi-config-folio-db-env
        image: 'folio/okapi:'
        name: folio-okapi
        ports:
        - containerPort: 9130
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/bin/folio/startup.sh
          name: okapi-claim0
      restartPolicy: Always
      volumes:
      - name: okapi-claim0
        persistentVolumeClaim:
          claimName: okapi-claim0
status: {}
