apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "16"
    field.cattle.io/creatorId: u-d8jfk
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-folio-q2-mod-calendar
  name: mod-calendar
  selfLink: /apis/apps/v1beta2/namespaces/folio-q2/deployments/mod-calendar
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-q2-mod-calendar
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-folio-q2-mod-calendar
    spec:
      affinity: {}
      containers:
      - env:
        - name: db.port
          value: "5432"
        - name: db.username
          value: folio_admin
        - name: db.database
          value: okapi_modules
        - name: db.host
          value: pg-folio
        - name: db.password
          value: folio_admin
        image: folioci/mod-calendar:1.0.0-SNAPSHOT.37
        imagePullPolicy: Always
        name: mod-calendar
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: dockerhub
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
