apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    field.cattle.io/creatorId: u-d8jfk
    field.cattle.io/publicEndpoints: '[{"addresses":["<xxx.xxx.xxx.xxx>"],"port":443,"protocol":"HTTPS","serviceName":"folio-q2:okapi","ingressName":"folio-q2:okapi","hostname":"myfolio-node-1.org","path":"/","allNodes":true},{"addresses":["<xxx.xxx.xxx.xxx>"],"port":443,"protocol":"HTTPS","serviceName":"folio-q2:okapi","ingressName":"folio-q2:okapi","hostname":"myfolio-node-1.org","path":"/_/","allNodes":true},{"addresses":["<xxx.xxx.xxx.xxx>"],"port":443,"protocol":"HTTPS","serviceName":"folio-q2:okapi","ingressName":"folio-q2:okapi","hostname":"myfolio-node-2.org","path":"/","allNodes":true},{"addresses":["<xxx.xxx.xxx.xxx>"],"port":443,"protocol":"HTTPS","serviceName":"folio-q2:okapi","ingressName":"folio-q2:okapi","hostname":"myfolio-node-2.org","path":"/_/","allNodes":true},{"addresses":["<xxx.xxx.xxx.xxx>"],"port":443,"protocol":"HTTPS","serviceName":"folio-q2:okapi","ingressName":"folio-q2:okapi","hostname":"myfolio-node-3.org","path":"/","allNodes":true},{"addresses":["<xxx.xxx.xxx.xxx>"],"port":443,"protocol":"HTTPS","serviceName":"folio-q2:okapi","ingressName":"folio-q2:okapi","hostname":"myfolio-node-3.org","path":"/_/","allNodes":true},{"addresses":["<xxx.xxx.xxx.xxx>"],"port":443,"protocol":"HTTPS","serviceName":"folio-q2:okapi","ingressName":"folio-q2:okapi","hostname":"folio-okapi-traffic-arecord.org","path":"/_/","allNodes":true},{"addresses":["<xxx.xxx.xxx.xxx>"],"port":443,"protocol":"HTTPS","serviceName":"folio-q2:okapi","ingressName":"folio-q2:okapi","hostname":"folio-okapi-traffic-arecord.org","allNodes":true},{"addresses":["<xxx.xxx.xxx.xxx>"],"port":443,"protocol":"HTTPS","serviceName":"folio-q2:okapi","ingressName":"folio-q2:okapi","hostname":"folio-okapi-traffic-arecord.org","path":"/","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-folio-q2-okapi
  name: okapi
  selfLink: /apis/apps/v1beta2/namespaces/folio-q2/deployments/okapi
spec:
  minReadySeconds: 30
  progressDeadlineSeconds: 120
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-folio-q2-okapi
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":9130,"dnsName":"okapi","kind":"ClusterIP","name":"9130tcp02","protocol":"TCP","sourcePort":0},{"containerPort":5701,"dnsName":"okapi","kind":"ClusterIP","name":"5701tcp02","protocol":"TCP","sourcePort":0},{"containerPort":5703,"dnsName":"okapi","kind":"ClusterIP","name":"5703tcp02","protocol":"TCP","sourcePort":0},{"containerPort":54327,"dnsName":"okapi","kind":"ClusterIP","name":"54327udp02","protocol":"UDP","sourcePort":0}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-folio-q2-okapi
    spec:
      affinity: {}
      containers:
      - env:
        - name: OKAPI_URL
          value: http://okapi:9130
        - name: HAZELCAST_PORT
          value: "5701"
        - name: HAZELCAST_VERTX_PORT
          value: "5703"
        - name: HAZELCAST_IP
          value: <Service ClusterIP>
        - name: OKAPI_NODENAME
          value: okapi1
        - name: OKAPI_PORT
          value: "9130"
        - name: OKAPI_LOGLEVEL
          value: INFO
        - name: PG_HOST
          value: pg-folio
        - name: INITDB
          value: "false"
        - name: OKAPI_CLUSTERHOST
          value: <Service ClusterIP>
        - name: OKAPI_HOST
          value: okapi
        image: <my-docker-private-registry>/folio/okapi:v1
        imagePullPolicy: Always
        name: okapi
        ports:
        - containerPort: 9130
          name: 9130tcp02
          protocol: TCP
        - containerPort: 5701
          name: 5701tcp02
          protocol: TCP
        - containerPort: 5703
          name: 5703tcp02
          protocol: TCP
        - containerPort: 54327
          name: 54327udp02
          protocol: UDP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: my-secret-name
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
