apiVersion: v1
data:
  PG_DATABASE: foobar
  PG_PASSWORD: foobar
  PG_PRIMARY_PASSWORD: foobar
  PG_PRIMARY_PORT: foobar
  PG_PRIMARY_USER: foobar
  PG_ROOT_PASSWORD: foobar
  PG_USER: foobar
kind: Secret
metadata:
  annotations:
    field.cattle.io/creatorId: u-foo
    field.cattle.io/projectId: c-f00:p-foo
  creationTimestamp: null
  labels:
    cattle.io/creator: norman
  name: db-config
  selfLink: /api/v1/namespaces/folio-q4/secrets/db-config
type: Opaque
